### ISSUE TITLE
Can't load image in interface nor create new project

### ISSUE THREAD

**Issue by YoannPa** [ixiumu/photopea#2]
Hi, 

This is a relatively recent issue: since few days I would say (1 month maximum).
Image drag and drop doesn't work anymore on [https://ixiumu.github.io/photopea/](https://ixiumu.github.io/photopea/)
Creating a new project, using the links in the work area, or from the File > New menu does not load anything anymore.

The browser's console show Error 400 messages from Pixabay.com
Maybe the problem is related... or not.

Any idea what's the problem ?
Thank you.

**Comment by dongqingWang1968** [comment]
Hello, 
           Happy new Year! 
           I've just noticed this project, and tried to play with it.... And the load image function doesn't work as well. But seems this is quite new issue from your description. is there any change at your browser or any other sider?

          Thanks

**Comment by YoannPa** [comment]
@dongqingWang1968 This version is far outdated. It's just not working anymore since a year.
I am closing this issue.

**Comment by dongqingWang1968** [comment]
Hi Yoann

       Thanks a lot for the quick response! 
     I believe all the javascript files are running locally at browser (i.e. not talking with server at all), then it's confusing me why such js codes can't work suddenly. Maybe, the original author did some magic in the javascript codes which I don't know. But anyway, thank you a lot for sharing this.

         Regards
         dongqing
